
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org2-chaincode-demo
  namespace: dummy-com
  labels: 
    chaincode: peer0-org2-chaincode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      chaincode: peer0-org2-chaincode-demo
  template:
    metadata:
      labels:
        chaincode: peer0-org2-chaincode-demo
    spec:
      containers:
        - name: peer0-org2-chaincode-demo
          image: basicj_ccaas_image
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: 0.0.0.0:9999
            - name: CORE_CHAINCODE_ID_NAME
              value: basic_1.0:04c7115f0b12be22e96d88e9072665b93254b1c3f1afa13722065545d6f9d347
          ports:
            - containerPort: 9999
