
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer2-org1-chaincode-demo
  namespace: dummy-com
  labels: 
    chaincode: peer2-org1-chaincode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      chaincode: peer2-org1-chaincode-demo
  template:
    metadata:
      labels:
        chaincode: peer2-org1-chaincode-demo
    spec:
      nodeName: worker1
      containers:
        - name: peer2-org1-chaincode-demo
          image: basicj_ccaas_image
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: 0.0.0.0:9999
            - name: CORE_CHAINCODE_ID_NAME
              value: basic_1.0:73241a8c9742aaab7bc5c9600d2fc9c1a9d6f9c74db08e927c34adefcea63cce
          ports:
            - containerPort: 9999
