#storageClassName: manual
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-share
    server: 172.16.1.82

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-2
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-share
    server: 172.16.1.82

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-3
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-share
    server: 172.16.1.82

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-4
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-share
    server: 172.16.1.82

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-5
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-share
    server: 172.16.1.82